// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import templruntime "github.com/a-h/templ/runtime"

var _ = templruntime.GeneratedTemplate
